name: Testing

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v6
              with:
                  persist-credentials: false

            - name: Setup
              uses: ./.github/actions/setup

            - name: Run build
              run: yarn ci

            - name: Run test suite with coverage
              run: yarn coverage

            - name: Upload coverage data
              uses: actions/upload-artifact@v7
              with:
                  name: coverage-data-${{ github.run_id }}
                  path: |
                      coverage/coverage*.json

            - name: Coverage summary
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: coverage/cobertura-coverage.xml
                  format: "markdown"
                  output: "both"

            - name: Add coverage PR comment
              uses: marocchino/sticky-pull-request-comment@v2.6.0
              with:
                  recreate: true
                  path: code-coverage-results.md

            - name: Write to job summary
              if: always()
              run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
