name: PR update

on:
    push:
        branches: [main]

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Auto-update open PRs targeting main
              uses: castastrophe/actions-pr-auto-update@v3
              with:
                  exclude_labels: renovate
